### PR TITLE
CMakeLists.txt: check jsk_topic_tools_VERSION to compile/test ColorHi…

### PR DESCRIPTION
**Pull request by k-okada**
…stogram functions

to pass travis test, currently hydro, and indigo/kinetic deb did not support 'isSubscribed' https://github.com/jsk-ros-pkg/jsk_common/pull/1523

BTW, why jsk_pcl_ros_utils, not jsk_pcl_ros ? is this utility tool?

### CODE REVIEW

**Comment by furushchev** [comment]
@k-okada Thank you very much!!!

**Comment by furushchev** [comment]
@k-okada 

> BTW, why jsk_pcl_ros_utils, not jsk_pcl_ros ? is this utility tool?

I heard from @wkentaro that `jsk_pcl_ros` is now almost full on build time, so it's better to put new nodelets or scripts on `jsk_pcl_ros_utils`.

**Comment by k-okada** [comment]
jsk_pcl_ros_utils, should put util program for jsk_pcl_ros and if you care about build time, we'd better to change travis.yml  settings, like separate build or add more packages to docker image in https://travis-ci.org/jsk-ros-pkg/jsk_recognition/jobs/248231192,
Otherwise, you'll here your student will complain I'd like to create new package, because the structure of jsk_pcl_ros and jsk_pcl_ros_utils are so mess.

**Comment by wkentaro** [comment]
@furushchev Maybe my last comment was not very correct, sorry. ColorHistogram-based programs usually put in jsk_pcl_ros, so it seems better that we put this program also there.
For saving build-time, we can move other utility functions that is still put in jsk_pcl_ros, for example, ExtractIndices.

**Comment by furushchev** [comment]
@wkentaro I see, thanks for advice anyway!
@k-okada So, need to re-create another pull request?

**Comment by wkentaro** [comment]
> @k-okada So, need to re-create another pull request?

I think you can move files from jsk_pcl_ros_utils to jsk_pcl_ros. why not?

**Pull request merged**
